---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      network:
        - ["forwarded_port", {guest: 8000, host: 8000}]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    attributes:
